// <auto-generated />
namespace ElDorado.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addededitorasaconcept : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addededitorasaconcept));
        
        string IMigrationMetadata.Id
        {
            get { return "201907061516262_Added editor as a concept"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
